name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get dependencies
      run: sudo apt update && sudo apt install cmake clang-9 llvm-9
      
    - name: configure
      working-directory: /home/runner/work/k_tree/k_tree
      run: cmake . -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_C_COMPILER=clang-9
      
    - name: run tests
      working-directory: /home/runner/work/k_tree/k_tree
      run: cmake --build . --config Release && ctest .
